package works.lysenko.util.apis.parameters;

/**
 *
 */
@SuppressWarnings("InterfaceWithOnlyOneDirectInheritor")
public interface _TestParameters {

    /**
     * Retrieves the name of the test.
     *
     * @return The name of the test as a string.
     */
    String getTest();

    /**
     * Sets the temporary (dynamic) name of the test.
     *
     * @param name The name of the test as a string.
     */
    void setTest(final String name);

    /**
     * Retrieves the pool value.
     *
     * @return the pool value as a string
     */
    String getPool();

    /**
     * Returns the description of the test.
     * The description is generated by concatenating the test name, pool, and domain,
     * providing additional context about the test.
     *
     * @return A string representing the complete test description.
     */
    String testDescription();
}
