package works.lysenko.util.apis.util;

import works.lysenko.base.Telemetry;
import works.lysenko.util.apis.scenario._Scenario;

import java.util.List;

import static works.lysenko.util.chrs.___.DOTS;
import static works.lysenko.util.data.strs.Case.c;
import static works.lysenko.util.data.strs.Swap.s;
import static works.lysenko.util.lang.word.I.INITIALIZATION;

/**
 * Provides a dashboard interface for displaying various components such as breadcrumbs, status board, and buttons.
 */
public interface _Dashboard {

    /**
     * Holds a string representation of the word "Initialization" concatenated with dots.
     * The string is generated by capitalizing the term "INITIALIZATION", appending it with
     * a predefined string, "DOTS", and then concatenating them using the helper function `s`.
     * The static utility methods `c` (capitalization) and `s` (string concatenation)
     * are employed here.
     */
    String initialization = s(c(INITIALIZATION), DOTS);

    /**
     * Releases any resources or performs any cleanup operations associated with this object.
     * <p>
     * This method is used to release any resources or perform any cleanup operations associated with an object.
     * It should be called when the object is no longer needed to free up resources or to perform any necessary cleanup tasks.
     * <p>
     * Note: This method does not take any parameters and does not return any v.
     */
    void dispose();

    /**
     * Determines if the execution is in debug mode.
     *
     * @return true if the execution is in debug mode, false otherwise
     */
    boolean isDebug();

    /**
     * Determines if the application is currently halted.
     *
     * @return true if the application is halted, false otherwise
     */
    boolean isHalt();

    /**
     * Sets the halt button of the dashboard.
     * <p>
     * This method updates the state of the halt button on the dashboard.
     * The halt button is used to control the execution of a process.
     *
     * @param active true if the halt button should be active, false otherwise
     */
    void setHalt(boolean active);

    /**
     * Determines if the application is currently paused.
     *
     * @return true if the application is paused, false otherwise
     */
    boolean isPause();

    /**
     * Determines if the execution is stopping.
     *
     * @return true if the execution is stopping, false otherwise
     */
    boolean isStop();

    /**
     * Sets the stop button of the dashboard.
     *
     * @param active true if the stop button should be active, false otherwise
     */
    void setStop(boolean active);

    /**
     * @param content of Breadcrumbs to add
     */
    void setBreadcrumb(List<? extends _Scenario> content);

    /**
     * @param message   of last/current log
     * @param telemetry record
     */
    void setInfo(String message, Telemetry telemetry);

    /**
     * Sets the title of the dashboard.
     * <p>
     * This method updates the title of the dashboard to the specified current test title. The title is displayed on the
     * dashboard.
     *
     * @param title the title of the current test to be set
     */
    void setTitle(String title);
}
